#!/usr/bin/env python3

def fibonacci(n):
    if n==1:
        return 1
    if n==2:
        return 2
    return fibonacci(n-1)+fibonacci(n-2)

def problem_2():
    """
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
    By starting with 1 and 2, the first 10 terms will be:
    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.
    """
    sum=0
    stop=100 #4000001
    for i in range(2,stop,2):
        sum+=fibonacci(i)
    return sum



if __name__ == "__main__":
    print( problem_2() )
    
